import React from 'react';

/**
 * The most safety-critical element in the product. Solid warning fill, white
 * bold text, 🧪 emoji — deliberately unlike the 15%-tint status pills so a
 * simulated record can never be mistaken for a real one at a glance.
 * Render it on EVERY view of a record carrying is_simulated: true, immediately
 * adjacent to the change-type badge. It is never omittable.
 */
export function SimulatedBadge({ style, ...rest }) {
  return (
    <span
      title="Generated by the simulation tool — not a real detected change"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        background: 'var(--simulated-bg)',
        color: 'var(--simulated-fg)',
        font: 'var(--type-meta)',
        fontWeight: 'var(--font-weight-bold)',
        letterSpacing: 'var(--label-letter-spacing)',
        borderRadius: 'var(--radius-sm)',
        padding: '3px 9px',
        whiteSpace: 'nowrap',
        ...style,
      }}
      {...rest}
    >
      <span aria-hidden="true">🧪</span>SIMULATED
    </span>
  );
}
